# playbook_hostname.yaml
---
- name: Configure hostname on Cisco IOS XE Router1
  hosts: router1 # Apply to all hosts in inventory
  gather_facts: false # No need to gather facts for this simple task
  
  vars:
    new_hostname: "Andy_Ansible-Managed-Router1" # Define the desired hostname

  tasks:
    - name: Set router1 hostname
      cisco.ios.ios_config:
        lines:
          - hostname {{ new_hostname }} # Use the variable
        save_when: changed # Save config if changes are made
      register: hostname_result # Store task result for inspection
      
    - name: Print hostname change result
      debug:
        msg: "Hostname configuration result: {{ hostname_result }}"
        